import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";
import { twoFactor } from "better-auth/plugins/two-factor";
import { db } from "@/db";
import * as schema from "@/db/schema";
import { env } from "@/env";
import { buildVerificationEmail, sendEmail } from "@/lib/email";
import { randomUUID } from "crypto";

/**
 * MediSoft C-OS authentication (Better-Auth, self-hosted).
 *
 * Phase 1: email + password.
 * Future: Nafath (Saudi national IAM), SSO for hospital groups, 2FA.
 *
 * Email verification:
 *   The verification plumbing is fully wired below — Better-Auth will
 *   call `sendVerificationEmail` when a new user signs up. Today that
 *   logs to the console (see src/lib/email). To turn verification into
 *   a hard requirement, flip `requireEmailVerification` to true in
 *   `emailAndPassword` AND configure a real email driver (Resend etc.).
 */
export const auth = betterAuth({
  appName: "MediSoft C-OS",
  baseURL: env.BETTER_AUTH_URL,
  secret: env.BETTER_AUTH_SECRET,

  /**
   * Trusted origins — allow the MediSport standalone subdomain
   * to call /api/auth/* endpoints without "Invalid origin" errors.
   */
  trustedOrigins: [
    "https://sport.medisofthealth.com",
    "https://app.medisofthealth.com",
  ],

  database: drizzleAdapter(db, {
    provider: "pg",
    schema: {
      user: schema.users,
      session: schema.sessions,
      account: schema.accounts,
      verification: schema.verifications,
      twoFactor: schema.twoFactor,
    },
  }),

  emailAndPassword: {
    enabled: true,
    // Production hardening: set to `true` AND configure a real email
    // driver (src/lib/email/index.ts) before flipping. Leaving false
    // means signups land instantly but the verification email is
    // still sent (visible in the console) so we can dry-run the flow.
    requireEmailVerification: false,
    minPasswordLength: 12, // healthcare-grade
    maxPasswordLength: 128,
    autoSignIn: true,
    /** Send the reset-password email (unused until reset flow ships). */
    sendResetPassword: async ({ user, url }) => {
      const { buildPasswordResetEmail } = await import("@/lib/email");
      await sendEmail(
        buildPasswordResetEmail({ toName: user.name, toEmail: user.email, url }),
      );
    },
  },

  emailVerification: {
    /** Send the verification link. Better-Auth invokes this on signup. */
    sendVerificationEmail: async ({ user, url }) => {
      await sendEmail(
        buildVerificationEmail({ toName: user.name, toEmail: user.email, url }),
      );
    },
    /** Mark the user as verified the first time they click the link. */
    autoSignInAfterVerification: true,
  },

  session: {
    expiresIn: 30 * 60, // 30 minutes of inactivity — medical environment security (HIPAA/PDPL)
    updateAge: 5 * 60, // refresh every 5 minutes of activity
    cookieCache: {
      enabled: true,
      maxAge: 5 * 60, // 5 minutes
    },
  },

  user: {
    additionalFields: {
      role: {
        type: "string",
        required: false,
        defaultValue: "physician",
        input: false, // not settable on signup; only admins promote
      },
      specialty: { type: "string", required: false },
      licenseNumber: { type: "string", required: false },
      saudiId: { type: "string", required: false },
    },
  },

  advanced: {
    cookiePrefix: "medisoft",
    useSecureCookies: true,
    /**
     * UUID FIX — Critical for PostgreSQL schema compatibility.
     *
     * Schema layout:
     *   - users.id     → uuid type with defaultRandom()
     *   - accounts.id  → text type, NO default
     *   - sessions.id  → text type, NO default
     *   - verifications.id → text type, NO default
     *
     * Problem with database.generateId = "uuid" (string):
     *   The adapter factory (get-id-field.mjs) sets shouldGenerateId = !supportsUUIDs.
     *   Since Drizzle pg adapter sets supportsUUIDs = true, shouldGenerateId = false.
     *   This means NO ID is generated by Better Auth — it relies on DB defaults.
     *   But only the users table has defaultRandom(); accounts/sessions/verifications
     *   have NO default → null ID → constraint violation.
     *
     * Solution: Use database.generateId as a FUNCTION (not the "uuid" string).
     *   When it's a function, useUUIDs = false, so shouldGenerateId = true.
     *   The defaultValue() in idField then calls our function → UUID for all models.
     *   UUID strings are valid for both uuid columns AND text columns.
     */
    database: {
      generateId: ({ model }: { model: string; size?: number }) => randomUUID(),
    },
  },

  plugins: [
    twoFactor({
      issuer: "MediSoft C-OS",
      totpOptions: {
        digits: 6,
        period: 30,
      },
      backupCodeOptions: {
        length: 10,
        characters: "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
      },
    }),
    nextCookies(), // must remain last in this list
  ],
});

export type Auth = typeof auth;
