/**
 * MediSport — Arabic Food Database
 *
 * Comprehensive food database with Arabic/English names,
 * macronutrient data, and Gulf/Arab cuisine focus.
 *
 * Data per 100g serving unless otherwise noted.
 */

export interface FoodItem {
  id: string;
  nameAr: string;
  nameEn: string;
  category: FoodCategory;
  servingSize: number; // grams
  servingUnit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  sugar: number;
  sodium: number; // mg
  tags: string[];
}

export type FoodCategory =
  | "grains"
  | "protein"
  | "dairy"
  | "fruits"
  | "vegetables"
  | "fats"
  | "beverages"
  | "sweets"
  | "meals"
  | "supplements";

export const FOOD_CATEGORIES: Record<FoodCategory, { ar: string; en: string; icon: string }> = {
  grains: { ar: "الحبوب والنشويات", en: "Grains & Starches", icon: "🌾" },
  protein: { ar: "البروتينات", en: "Proteins", icon: "🥩" },
  dairy: { ar: "الألبان", en: "Dairy", icon: "🥛" },
  fruits: { ar: "الفواكه", en: "Fruits", icon: "🍎" },
  vegetables: { ar: "الخضروات", en: "Vegetables", icon: "🥬" },
  fats: { ar: "الدهون والزيوت", en: "Fats & Oils", icon: "🫒" },
  beverages: { ar: "المشروبات", en: "Beverages", icon: "☕" },
  sweets: { ar: "الحلويات", en: "Sweets", icon: "🍯" },
  meals: { ar: "الوجبات الجاهزة", en: "Prepared Meals", icon: "🍽️" },
  supplements: { ar: "المكملات", en: "Supplements", icon: "💊" },
};

/**
 * Core Arabic food database — Gulf/Arab cuisine focus
 * Values per 100g unless servingSize specifies otherwise
 */
export const FOOD_DATABASE: FoodItem[] = [
  // ─── Grains & Starches ───────────────────────────────────
  {
    id: "rice-white",
    nameAr: "أرز أبيض مطبوخ",
    nameEn: "White Rice (cooked)",
    category: "grains",
    servingSize: 150,
    servingUnit: "cup",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    sugar: 0,
    sodium: 1,
    tags: ["staple", "gulf"],
  },
  {
    id: "rice-basmati",
    nameAr: "أرز بسمتي",
    nameEn: "Basmati Rice (cooked)",
    category: "grains",
    servingSize: 150,
    servingUnit: "cup",
    calories: 121,
    protein: 3.5,
    carbs: 25,
    fat: 0.4,
    fiber: 0.6,
    sugar: 0,
    sodium: 1,
    tags: ["staple", "gulf"],
  },
  {
    id: "bread-arabic",
    nameAr: "خبز عربي",
    nameEn: "Arabic Flatbread",
    category: "grains",
    servingSize: 60,
    servingUnit: "piece",
    calories: 275,
    protein: 9,
    carbs: 55,
    fat: 1.2,
    fiber: 2.2,
    sugar: 1.5,
    sodium: 536,
    tags: ["staple", "gulf"],
  },
  {
    id: "bread-samoon",
    nameAr: "صمون عراقي",
    nameEn: "Samoon Bread",
    category: "grains",
    servingSize: 80,
    servingUnit: "piece",
    calories: 290,
    protein: 9.5,
    carbs: 56,
    fat: 2.5,
    fiber: 2,
    sugar: 2,
    sodium: 480,
    tags: ["staple", "iraqi"],
  },
  {
    id: "oats",
    nameAr: "شوفان",
    nameEn: "Oats (dry)",
    category: "grains",
    servingSize: 40,
    servingUnit: "cup",
    calories: 389,
    protein: 16.9,
    carbs: 66,
    fat: 6.9,
    fiber: 10.6,
    sugar: 0,
    sodium: 2,
    tags: ["healthy", "breakfast"],
  },
  {
    id: "pasta-cooked",
    nameAr: "معكرونة مطبوخة",
    nameEn: "Pasta (cooked)",
    category: "grains",
    servingSize: 140,
    servingUnit: "cup",
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 1.8,
    sugar: 0.6,
    sodium: 1,
    tags: ["staple"],
  },
  {
    id: "freekeh",
    nameAr: "فريكة",
    nameEn: "Freekeh (cooked)",
    category: "grains",
    servingSize: 130,
    servingUnit: "cup",
    calories: 130,
    protein: 5.5,
    carbs: 22,
    fat: 1.5,
    fiber: 4.5,
    sugar: 0,
    sodium: 5,
    tags: ["healthy", "arab", "high-fiber"],
  },
  {
    id: "bulgur",
    nameAr: "برغل",
    nameEn: "Bulgur (cooked)",
    category: "grains",
    servingSize: 130,
    servingUnit: "cup",
    calories: 83,
    protein: 3.1,
    carbs: 18.6,
    fat: 0.2,
    fiber: 4.5,
    sugar: 0.1,
    sodium: 5,
    tags: ["healthy", "arab", "high-fiber"],
  },

  // ─── Proteins ────────────────────────────────────────────
  {
    id: "chicken-breast",
    nameAr: "صدر دجاج مشوي",
    nameEn: "Grilled Chicken Breast",
    category: "protein",
    servingSize: 120,
    servingUnit: "piece",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    sugar: 0,
    sodium: 74,
    tags: ["lean", "high-protein"],
  },
  {
    id: "lamb-meat",
    nameAr: "لحم ضأن",
    nameEn: "Lamb Meat (cooked)",
    category: "protein",
    servingSize: 100,
    servingUnit: "piece",
    calories: 258,
    protein: 25.6,
    carbs: 0,
    fat: 16.5,
    fiber: 0,
    sugar: 0,
    sodium: 72,
    tags: ["gulf", "high-protein"],
  },
  {
    id: "fish-hammour",
    nameAr: "سمك هامور",
    nameEn: "Hammour Fish (Grouper)",
    category: "protein",
    servingSize: 150,
    servingUnit: "fillet",
    calories: 92,
    protein: 19.4,
    carbs: 0,
    fat: 1.3,
    fiber: 0,
    sugar: 0,
    sodium: 53,
    tags: ["gulf", "lean", "omega-3"],
  },
  {
    id: "shrimp",
    nameAr: "روبيان (جمبري)",
    nameEn: "Shrimp",
    category: "protein",
    servingSize: 100,
    servingUnit: "serving",
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0,
    sugar: 0,
    sodium: 111,
    tags: ["gulf", "lean", "seafood"],
  },
  {
    id: "eggs",
    nameAr: "بيض مسلوق",
    nameEn: "Boiled Eggs",
    category: "protein",
    servingSize: 50,
    servingUnit: "egg",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    sugar: 1.1,
    sodium: 124,
    tags: ["breakfast", "versatile"],
  },
  {
    id: "lentils",
    nameAr: "عدس مطبوخ",
    nameEn: "Cooked Lentils",
    category: "protein",
    servingSize: 130,
    servingUnit: "cup",
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 7.9,
    sugar: 1.8,
    sodium: 2,
    tags: ["plant-based", "high-fiber", "arab"],
  },
  {
    id: "chickpeas",
    nameAr: "حمص مطبوخ",
    nameEn: "Cooked Chickpeas",
    category: "protein",
    servingSize: 130,
    servingUnit: "cup",
    calories: 164,
    protein: 8.9,
    carbs: 27,
    fat: 2.6,
    fiber: 7.6,
    sugar: 4.8,
    sodium: 7,
    tags: ["plant-based", "arab", "high-fiber"],
  },
  {
    id: "tuna-canned",
    nameAr: "تونة معلبة",
    nameEn: "Canned Tuna (in water)",
    category: "protein",
    servingSize: 85,
    servingUnit: "can",
    calories: 116,
    protein: 25.5,
    carbs: 0,
    fat: 0.8,
    fiber: 0,
    sugar: 0,
    sodium: 320,
    tags: ["lean", "convenient", "high-protein"],
  },

  // ─── Dairy ───────────────────────────────────────────────
  {
    id: "laban",
    nameAr: "لبن",
    nameEn: "Laban (Buttermilk)",
    category: "dairy",
    servingSize: 200,
    servingUnit: "cup",
    calories: 62,
    protein: 3.3,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    sugar: 4.8,
    sodium: 105,
    tags: ["gulf", "probiotic"],
  },
  {
    id: "yogurt-greek",
    nameAr: "زبادي يوناني",
    nameEn: "Greek Yogurt",
    category: "dairy",
    servingSize: 170,
    servingUnit: "cup",
    calories: 59,
    protein: 10,
    carbs: 3.6,
    fat: 0.7,
    fiber: 0,
    sugar: 3.2,
    sodium: 36,
    tags: ["high-protein", "healthy"],
  },
  {
    id: "cheese-halloumi",
    nameAr: "جبنة حلوم",
    nameEn: "Halloumi Cheese",
    category: "dairy",
    servingSize: 30,
    servingUnit: "slice",
    calories: 321,
    protein: 25,
    carbs: 2.6,
    fat: 25,
    fiber: 0,
    sugar: 2.6,
    sodium: 1390,
    tags: ["gulf", "high-protein"],
  },
  {
    id: "cheese-akkawi",
    nameAr: "جبنة عكاوي",
    nameEn: "Akkawi Cheese",
    category: "dairy",
    servingSize: 30,
    servingUnit: "slice",
    calories: 289,
    protein: 18,
    carbs: 1.5,
    fat: 23,
    fiber: 0,
    sugar: 1.5,
    sodium: 1200,
    tags: ["arab", "breakfast"],
  },
  {
    id: "milk-full",
    nameAr: "حليب كامل الدسم",
    nameEn: "Whole Milk",
    category: "dairy",
    servingSize: 240,
    servingUnit: "cup",
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    sugar: 5,
    sodium: 43,
    tags: ["staple"],
  },

  // ─── Fruits ──────────────────────────────────────────────
  {
    id: "dates-medjool",
    nameAr: "تمر مجدول",
    nameEn: "Medjool Dates",
    category: "fruits",
    servingSize: 24,
    servingUnit: "date",
    calories: 277,
    protein: 1.8,
    carbs: 75,
    fat: 0.2,
    fiber: 6.7,
    sugar: 66,
    sodium: 1,
    tags: ["gulf", "energy", "natural-sugar"],
  },
  {
    id: "dates-khalas",
    nameAr: "تمر خلاص",
    nameEn: "Khalas Dates",
    category: "fruits",
    servingSize: 20,
    servingUnit: "date",
    calories: 282,
    protein: 2.5,
    carbs: 73,
    fat: 0.4,
    fiber: 8,
    sugar: 63,
    sodium: 2,
    tags: ["gulf", "energy", "emirati"],
  },
  {
    id: "banana",
    nameAr: "موز",
    nameEn: "Banana",
    category: "fruits",
    servingSize: 118,
    servingUnit: "medium",
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    sugar: 12,
    sodium: 1,
    tags: ["energy", "potassium"],
  },
  {
    id: "watermelon",
    nameAr: "بطيخ",
    nameEn: "Watermelon",
    category: "fruits",
    servingSize: 280,
    servingUnit: "slice",
    calories: 30,
    protein: 0.6,
    carbs: 7.6,
    fat: 0.2,
    fiber: 0.4,
    sugar: 6.2,
    sodium: 1,
    tags: ["hydrating", "summer"],
  },
  {
    id: "mango",
    nameAr: "مانجو",
    nameEn: "Mango",
    category: "fruits",
    servingSize: 165,
    servingUnit: "cup",
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    fiber: 1.6,
    sugar: 14,
    sodium: 1,
    tags: ["tropical", "vitamin-c"],
  },
  {
    id: "apple",
    nameAr: "تفاح",
    nameEn: "Apple",
    category: "fruits",
    servingSize: 182,
    servingUnit: "medium",
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    sugar: 10,
    sodium: 1,
    tags: ["fiber", "snack"],
  },

  // ─── Vegetables ──────────────────────────────────────────
  {
    id: "cucumber",
    nameAr: "خيار",
    nameEn: "Cucumber",
    category: "vegetables",
    servingSize: 100,
    servingUnit: "medium",
    calories: 15,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    sugar: 1.7,
    sodium: 2,
    tags: ["hydrating", "salad"],
  },
  {
    id: "tomato",
    nameAr: "طماطم",
    nameEn: "Tomato",
    category: "vegetables",
    servingSize: 123,
    servingUnit: "medium",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    sugar: 2.6,
    sodium: 5,
    tags: ["salad", "versatile"],
  },
  {
    id: "spinach",
    nameAr: "سبانخ",
    nameEn: "Spinach (raw)",
    category: "vegetables",
    servingSize: 30,
    servingUnit: "cup",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    sugar: 0.4,
    sodium: 79,
    tags: ["iron", "superfood"],
  },
  {
    id: "sweet-potato",
    nameAr: "بطاطا حلوة",
    nameEn: "Sweet Potato (baked)",
    category: "vegetables",
    servingSize: 130,
    servingUnit: "medium",
    calories: 90,
    protein: 2,
    carbs: 21,
    fat: 0.1,
    fiber: 3.3,
    sugar: 6.5,
    sodium: 36,
    tags: ["complex-carbs", "healthy"],
  },
  {
    id: "avocado",
    nameAr: "أفوكادو",
    nameEn: "Avocado",
    category: "vegetables",
    servingSize: 68,
    servingUnit: "half",
    calories: 160,
    protein: 2,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    sugar: 0.7,
    sodium: 7,
    tags: ["healthy-fat", "superfood"],
  },

  // ─── Fats & Oils ─────────────────────────────────────────
  {
    id: "olive-oil",
    nameAr: "زيت زيتون",
    nameEn: "Olive Oil",
    category: "fats",
    servingSize: 14,
    servingUnit: "tbsp",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    sugar: 0,
    sodium: 2,
    tags: ["healthy-fat", "arab", "cooking"],
  },
  {
    id: "tahini",
    nameAr: "طحينة",
    nameEn: "Tahini",
    category: "fats",
    servingSize: 15,
    servingUnit: "tbsp",
    calories: 595,
    protein: 17,
    carbs: 21,
    fat: 54,
    fiber: 9.3,
    sugar: 0.5,
    sodium: 115,
    tags: ["arab", "calcium", "healthy-fat"],
  },
  {
    id: "almonds",
    nameAr: "لوز",
    nameEn: "Almonds",
    category: "fats",
    servingSize: 28,
    servingUnit: "handful",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12.5,
    sugar: 4.4,
    sodium: 1,
    tags: ["healthy-fat", "snack", "protein"],
  },
  {
    id: "peanut-butter",
    nameAr: "زبدة الفول السوداني",
    nameEn: "Peanut Butter",
    category: "fats",
    servingSize: 32,
    servingUnit: "tbsp",
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
    sugar: 9,
    sodium: 17,
    tags: ["high-protein", "energy"],
  },

  // ─── Beverages ───────────────────────────────────────────
  {
    id: "arabic-coffee",
    nameAr: "قهوة عربية",
    nameEn: "Arabic Coffee",
    category: "beverages",
    servingSize: 100,
    servingUnit: "cup",
    calories: 2,
    protein: 0.1,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 2,
    tags: ["gulf", "caffeine"],
  },
  {
    id: "green-tea",
    nameAr: "شاي أخضر",
    nameEn: "Green Tea",
    category: "beverages",
    servingSize: 240,
    servingUnit: "cup",
    calories: 2,
    protein: 0.5,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 2,
    tags: ["antioxidant", "healthy"],
  },
  {
    id: "protein-shake",
    nameAr: "مخفوق بروتين",
    nameEn: "Protein Shake (whey)",
    category: "beverages",
    servingSize: 30,
    servingUnit: "scoop",
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 1.5,
    fiber: 0,
    sugar: 1,
    sodium: 130,
    tags: ["supplement", "high-protein", "post-workout"],
  },

  // ─── Prepared Meals (Gulf) ───────────────────────────────
  {
    id: "kabsa",
    nameAr: "كبسة دجاج",
    nameEn: "Chicken Kabsa",
    category: "meals",
    servingSize: 350,
    servingUnit: "plate",
    calories: 210,
    protein: 14,
    carbs: 25,
    fat: 6,
    fiber: 1.5,
    sugar: 2,
    sodium: 580,
    tags: ["gulf", "saudi", "main-course"],
  },
  {
    id: "machboos",
    nameAr: "مجبوس لحم",
    nameEn: "Lamb Machboos",
    category: "meals",
    servingSize: 350,
    servingUnit: "plate",
    calories: 245,
    protein: 16,
    carbs: 28,
    fat: 8,
    fiber: 2,
    sugar: 2,
    sodium: 620,
    tags: ["gulf", "emirati", "kuwaiti", "main-course"],
  },
  {
    id: "shawarma-chicken",
    nameAr: "شاورما دجاج",
    nameEn: "Chicken Shawarma",
    category: "meals",
    servingSize: 200,
    servingUnit: "sandwich",
    calories: 230,
    protein: 18,
    carbs: 20,
    fat: 9,
    fiber: 1,
    sugar: 2,
    sodium: 680,
    tags: ["arab", "fast-food"],
  },
  {
    id: "hummus",
    nameAr: "حمص بالطحينة",
    nameEn: "Hummus",
    category: "meals",
    servingSize: 100,
    servingUnit: "serving",
    calories: 166,
    protein: 7.9,
    carbs: 14.3,
    fat: 9.6,
    fiber: 6,
    sugar: 0.3,
    sodium: 379,
    tags: ["arab", "appetizer", "plant-based"],
  },
  {
    id: "falafel",
    nameAr: "فلافل",
    nameEn: "Falafel",
    category: "meals",
    servingSize: 17,
    servingUnit: "piece",
    calories: 333,
    protein: 13,
    carbs: 32,
    fat: 18,
    fiber: 5,
    sugar: 0,
    sodium: 294,
    tags: ["arab", "plant-based", "fried"],
  },
  {
    id: "tabbouleh",
    nameAr: "تبولة",
    nameEn: "Tabbouleh",
    category: "meals",
    servingSize: 130,
    servingUnit: "cup",
    calories: 85,
    protein: 2,
    carbs: 9,
    fat: 5,
    fiber: 2,
    sugar: 1.5,
    sodium: 180,
    tags: ["arab", "salad", "healthy"],
  },
  {
    id: "fattoush",
    nameAr: "فتوش",
    nameEn: "Fattoush",
    category: "meals",
    servingSize: 150,
    servingUnit: "bowl",
    calories: 95,
    protein: 2.5,
    carbs: 12,
    fat: 4.5,
    fiber: 2.5,
    sugar: 3,
    sodium: 220,
    tags: ["arab", "salad", "healthy"],
  },

  // ─── Sweets ──────────────────────────────────────────────
  {
    id: "kunafa",
    nameAr: "كنافة",
    nameEn: "Kunafa",
    category: "sweets",
    servingSize: 100,
    servingUnit: "piece",
    calories: 380,
    protein: 7,
    carbs: 45,
    fat: 19,
    fiber: 1,
    sugar: 30,
    sodium: 180,
    tags: ["arab", "dessert"],
  },
  {
    id: "baklava",
    nameAr: "بقلاوة",
    nameEn: "Baklava",
    category: "sweets",
    servingSize: 40,
    servingUnit: "piece",
    calories: 428,
    protein: 6,
    carbs: 43,
    fat: 27,
    fiber: 2,
    sugar: 28,
    sodium: 200,
    tags: ["arab", "dessert", "nuts"],
  },
  {
    id: "luqaimat",
    nameAr: "لقيمات",
    nameEn: "Luqaimat",
    category: "sweets",
    servingSize: 30,
    servingUnit: "piece",
    calories: 350,
    protein: 4,
    carbs: 50,
    fat: 15,
    fiber: 1,
    sugar: 25,
    sodium: 150,
    tags: ["gulf", "emirati", "dessert"],
  },

  // ─── Supplements ─────────────────────────────────────────
  {
    id: "whey-protein",
    nameAr: "واي بروتين",
    nameEn: "Whey Protein Isolate",
    category: "supplements",
    servingSize: 30,
    servingUnit: "scoop",
    calories: 110,
    protein: 25,
    carbs: 1,
    fat: 0.5,
    fiber: 0,
    sugar: 0.5,
    sodium: 90,
    tags: ["supplement", "high-protein", "post-workout"],
  },
  {
    id: "creatine",
    nameAr: "كرياتين",
    nameEn: "Creatine Monohydrate",
    category: "supplements",
    servingSize: 5,
    servingUnit: "scoop",
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    tags: ["supplement", "performance"],
  },
  {
    id: "bcaa",
    nameAr: "أحماض أمينية متفرعة",
    nameEn: "BCAA",
    category: "supplements",
    servingSize: 7,
    servingUnit: "scoop",
    calories: 10,
    protein: 2.5,
    carbs: 0,
    fat: 0,
    fiber: 0,
    sugar: 0,
    sodium: 0,
    tags: ["supplement", "recovery"],
  },
];

/**
 * Search food items by name (Arabic or English)
 */
export function searchFood(query: string, locale: "ar" | "en" = "en"): FoodItem[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  return FOOD_DATABASE.filter((item) => {
    const nameField = locale === "ar" ? item.nameAr : item.nameEn;
    return (
      nameField.toLowerCase().includes(q) ||
      item.nameAr.includes(q) ||
      item.nameEn.toLowerCase().includes(q) ||
      item.tags.some((tag) => tag.includes(q))
    );
  });
}

/**
 * Get food items by category
 */
export function getFoodByCategory(category: FoodCategory): FoodItem[] {
  return FOOD_DATABASE.filter((item) => item.category === category);
}

/**
 * Calculate nutrition for a given serving
 */
export function calculateNutrition(item: FoodItem, grams: number) {
  const factor = grams / 100;
  return {
    calories: Math.round(item.calories * factor),
    protein: Math.round(item.protein * factor * 10) / 10,
    carbs: Math.round(item.carbs * factor * 10) / 10,
    fat: Math.round(item.fat * factor * 10) / 10,
    fiber: Math.round(item.fiber * factor * 10) / 10,
    sugar: Math.round(item.sugar * factor * 10) / 10,
    sodium: Math.round(item.sodium * factor),
  };
}
