"use client";

/**
 * MediSport Phase 7 — AthleteProgressPdf (shared, DB-backed)
 *
 * A self-contained "Export PDF" control that aggregates the athlete's full
 * MediSport progress — body composition, biological age, recent activity, and
 * the latest lab report — into a branded, printable PDF report.
 *
 * Data is pulled from the existing protected endpoints:
 *   - GET /api/sport?action=my-body-measurements
 *   - GET /api/sport?action=my-bio-age
 *   - GET /api/sport?action=my-activities
 *   - GET /api/sport?action=my-lab-results
 *
 * It is used by both the standalone `(sport)` trainee pages and (optionally)
 * the integrated `/medisport` module — true mirroring. The athlete name is read
 * from the client session; an optional `athleteName` prop lets a coach export a
 * report on a linked trainee's behalf without a session lookup.
 *
 * PDF rendering reuses the project's proven jsPDF + html2canvas pattern
 * (oklch/lab color sanitization before capture) used in MediLab.
 */

import * as React from "react";
import { useLocale } from "next-intl";
import { toast } from "sonner";
import { FileDown, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useSession } from "@/lib/auth-client";

// ── Data shapes (mirrors the API responses) ──────────────────────────────────
type Measurement = {
  id: string;
  measuredAt: string;
  weightKg: string | null;
  bodyFatPct: string | null;
  muscleMassKg: string | null;
  waterPct: string | null;
  waistCm: string | null;
  note: string | null;
};
type BodyComparison = {
  from: string;
  to: string;
  weightKg: number | null;
  bodyFatPct: number | null;
  muscleMassKg: number | null;
  waistCm: number | null;
} | null;
type BioAgeRecord = {
  id: string;
  chronologicalAge: string;
  biologicalAge: string;
  ageDelta: string;
  percentile: number | null;
  classification: string | null;
  createdAt: string;
};
type Activity = {
  id: string;
  activityType: string;
  startedAt: string;
  durationSec: number;
  distanceMeters: string;
  caloriesBurned: string;
};
type LabMarker = {
  name: string;
  category: string;
  value: number;
  unit: string;
  athleteMin?: number;
  athleteMax?: number;
};
type LabReport = {
  id: string;
  title: string;
  reportDate: string;
  seasonPhase: string | null;
  markers: LabMarker[];
  note: string | null;
};

type Bundle = {
  body: Measurement[];
  bodyComparison: BodyComparison;
  bioAge: BioAgeRecord[];
  activities: Activity[];
  labs: LabReport[];
};

// ── i18n micro-dictionary (no extra namespace needed) ────────────────────────
function dict(isAr: boolean) {
  const t = (ar: string, en: string) => (isAr ? ar : en);
  return {
    exportBtn: t("تصدير PDF", "Export PDF"),
    preparing: t("جارٍ التحضير…", "Preparing…"),
    reportTitle: t("تقرير تقدّم الرياضي", "Athlete Progress Report"),
    generatedBy: t("تم إنشاؤه بواسطة ميديسبورت", "Generated by MediSport"),
    athlete: t("الرياضي", "Athlete"),
    date: t("التاريخ", "Date"),
    period: t("الفترة", "Period"),
    bodyComp: t("تكوين الجسم", "Body Composition"),
    bioAgeSec: t("العمر البيولوجي", "Biological Age"),
    activitySec: t("النشاط (آخر ٣٠ يومًا)", "Activity (Last 30 Days)"),
    labsSec: t("أحدث تقرير تحاليل", "Latest Lab Report"),
    latest: t("الأحدث", "Latest"),
    change: t("التغيّر", "Change"),
    metric: t("المؤشر", "Metric"),
    weight: t("الوزن (كجم)", "Weight (kg)"),
    bodyFat: t("نسبة الدهون (٪)", "Body Fat (%)"),
    muscle: t("الكتلة العضلية (كجم)", "Muscle Mass (kg)"),
    water: t("نسبة الماء (٪)", "Water (%)"),
    waist: t("محيط الخصر (سم)", "Waist (cm)"),
    chronoAge: t("العمر الزمني", "Chronological Age"),
    bioAgeLbl: t("العمر البيولوجي", "Biological Age"),
    delta: t("الفارق", "Difference"),
    percentile: t("المئين", "Percentile"),
    years: t("سنة", "yrs"),
    younger: t("أصغر", "younger"),
    older: t("أكبر", "older"),
    sessions: t("الجلسات", "Sessions"),
    totalDistance: t("إجمالي المسافة", "Total Distance"),
    totalDuration: t("إجمالي المدة", "Total Duration"),
    totalCalories: t("إجمالي السعرات", "Total Calories"),
    km: t("كم", "km"),
    kcal: t("سعرة", "kcal"),
    marker: t("التحليل", "Marker"),
    value: t("القيمة", "Value"),
    range: t("النطاق الرياضي", "Athlete Range"),
    statusLbl: t("الحالة", "Status"),
    inRange: t("ضمن النطاق", "In range"),
    outRange: t("خارج النطاق", "Out of range"),
    seasonPhase: t("مرحلة الموسم", "Season Phase"),
    noData: t("لا توجد بيانات مسجّلة بعد", "No data recorded yet"),
    noBody: t("لم تُسجّل قياسات جسم بعد", "No body measurements recorded yet"),
    noBio: t("لم يُحسب العمر البيولوجي بعد", "Biological age not calculated yet"),
    noActivity: t("لا يوجد نشاط في آخر ٣٠ يومًا", "No activity in the last 30 days"),
    noLabs: t("لا توجد تقارير تحاليل بعد", "No lab reports recorded yet"),
    fail: t("تعذّر إنشاء التقرير", "Failed to generate report"),
    empty: t("لا توجد بيانات كافية للتصدير", "Not enough data to export"),
    confidential: t(
      "وثيقة سرّية — لمشاركتها مع الفريق الطبي والتدريبي فقط.",
      "Confidential — for sharing with the medical and coaching team only.",
    ),
  };
}

const ACTIVITY_LABELS: Record<string, { ar: string; en: string }> = {
  run: { ar: "جري", en: "Run" },
  walk: { ar: "مشي", en: "Walk" },
  cycle: { ar: "دراجة", en: "Cycle" },
  swim: { ar: "سباحة", en: "Swim" },
  gym: { ar: "صالة", en: "Gym" },
};

function fmtDate(iso: string | null, isAr: boolean): string {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleDateString(isAr ? "ar-EG" : "en-GB", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  } catch {
    return iso.slice(0, 10);
  }
}

function num(v: unknown): number | null {
  if (v === null || v === undefined || v === "") return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

export function AthleteProgressPdf({
  athleteName,
  className,
  variant = "outline",
  size = "sm",
}: {
  athleteName?: string;
  className?: string;
  variant?: "outline" | "default" | "ghost";
  size?: "sm" | "md" | "lg" | "icon";
}) {
  const locale = useLocale() as "ar" | "en";
  const isAr = locale === "ar";
  const d = dict(isAr);
  const { data: session } = useSession();
  const [busy, setBusy] = React.useState(false);

  const resolvedName =
    athleteName || session?.user?.name || session?.user?.email || d.athlete;

  const fetchBundle = async (): Promise<Bundle> => {
    const get = async (action: string) => {
      const res = await fetch(`/api/sport?action=${action}`);
      if (!res.ok) return { success: false };
      return res.json();
    };
    const [b, bio, act, lab] = await Promise.all([
      get("my-body-measurements"),
      get("my-bio-age"),
      get("my-activities"),
      get("my-lab-results"),
    ]);
    return {
      body: b?.success ? (b.data as Measurement[]) : [],
      bodyComparison: b?.success ? (b.comparison as BodyComparison) : null,
      bioAge: bio?.success ? (bio.data as BioAgeRecord[]) : [],
      activities: act?.success ? (act.data as Activity[]) : [],
      labs: lab?.success ? (lab.data as LabReport[]) : [],
    };
  };

  const buildReportHtml = (bundle: Bundle): string => {
    const { body, bodyComparison, bioAge, activities, labs } = bundle;
    const dir = isAr ? "rtl" : "ltr";
    const align = isAr ? "right" : "left";

    // ── Body composition ──
    const latestBody = body[body.length - 1] || null;
    const bodyRows = (() => {
      if (!latestBody) {
        return `<tr><td colspan="3" style="padding:14px;color:#94a3b8;text-align:center">${d.noBody}</td></tr>`;
      }
      const c = bodyComparison;
      const row = (label: string, latest: number | null, change: number | null) => {
        if (latest === null) return "";
        const chg =
          change === null
            ? "—"
            : `<span style="color:${change < 0 ? "#059669" : change > 0 ? "#dc2626" : "#64748b"}">${change > 0 ? "+" : ""}${change}</span>`;
        return `<tr>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0">${label}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0;font-weight:600">${latest}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #e2e8f0">${chg}</td>
        </tr>`;
      };
      return [
        row(d.weight, num(latestBody.weightKg), c?.weightKg ?? null),
        row(d.bodyFat, num(latestBody.bodyFatPct), c?.bodyFatPct ?? null),
        row(d.muscle, num(latestBody.muscleMassKg), c?.muscleMassKg ?? null),
        row(d.water, num(latestBody.waterPct), null),
        row(d.waist, num(latestBody.waistCm), c?.waistCm ?? null),
      ].join("");
    })();

    // ── Bio age ──
    const latestBio = bioAge[0] || null;
    const bioBlock = (() => {
      if (!latestBio) {
        return `<p style="padding:14px 0;color:#94a3b8;text-align:center">${d.noBio}</p>`;
      }
      const delta = num(latestBio.ageDelta) ?? 0;
      const deltaTxt =
        delta < 0
          ? `${Math.abs(delta)} ${d.years} ${d.younger}`
          : delta > 0
            ? `${delta} ${d.years} ${d.older}`
            : "—";
      const deltaColor = delta < 0 ? "#059669" : delta > 0 ? "#dc2626" : "#64748b";
      const stat = (label: string, value: string, color = "#0f172a") =>
        `<div style="flex:1;text-align:center;padding:10px;border:1px solid #e2e8f0;border-radius:10px;margin:0 4px">
          <div style="font-size:11px;color:#64748b">${label}</div>
          <div style="font-size:20px;font-weight:700;color:${color};margin-top:2px">${value}</div>
        </div>`;
      return `<div style="display:flex;gap:0;margin-top:6px">
        ${stat(d.chronoAge, `${num(latestBio.chronologicalAge) ?? "—"}`)}
        ${stat(d.bioAgeLbl, `${num(latestBio.biologicalAge) ?? "—"}`, "#0d9488")}
        ${stat(d.delta, deltaTxt, deltaColor)}
        ${stat(d.percentile, latestBio.percentile != null ? `${latestBio.percentile}%` : "—")}
      </div>`;
    })();

    // ── Activity (last 30 days) ──
    const cutoff = Date.now() - 30 * 86400000;
    const recent = activities.filter((a) => new Date(a.startedAt).getTime() >= cutoff);
    const actBlock = (() => {
      if (recent.length === 0) {
        return `<p style="padding:14px 0;color:#94a3b8;text-align:center">${d.noActivity}</p>`;
      }
      const totalDist = recent.reduce((s, a) => s + (num(a.distanceMeters) ?? 0), 0) / 1000;
      const totalDur = recent.reduce((s, a) => s + (a.durationSec ?? 0), 0);
      const totalCal = recent.reduce((s, a) => s + (num(a.caloriesBurned) ?? 0), 0);
      const hrs = Math.floor(totalDur / 3600);
      const mins = Math.round((totalDur % 3600) / 60);
      const durTxt = hrs > 0 ? `${hrs}h ${mins}m` : `${mins}m`;
      const stat = (label: string, value: string) =>
        `<div style="flex:1;text-align:center;padding:10px;border:1px solid #e2e8f0;border-radius:10px;margin:0 4px">
          <div style="font-size:11px;color:#64748b">${label}</div>
          <div style="font-size:18px;font-weight:700;color:#059669;margin-top:2px">${value}</div>
        </div>`;
      // activity-type counts
      const counts: Record<string, number> = {};
      recent.forEach((a) => {
        counts[a.activityType] = (counts[a.activityType] || 0) + 1;
      });
      const breakdown = Object.entries(counts)
        .map(([type, n]) => {
          const lbl = ACTIVITY_LABELS[type] ? (isAr ? ACTIVITY_LABELS[type].ar : ACTIVITY_LABELS[type].en) : type;
          return `${lbl}: ${n}`;
        })
        .join(" · ");
      return `<div style="display:flex;gap:0;margin-top:6px">
          ${stat(d.sessions, `${recent.length}`)}
          ${stat(d.totalDistance, `${totalDist.toFixed(1)} ${d.km}`)}
          ${stat(d.totalDuration, durTxt)}
          ${stat(d.totalCalories, `${Math.round(totalCal)}`)}
        </div>
        <p style="margin-top:8px;font-size:12px;color:#64748b">${breakdown}</p>`;
    })();

    // ── Latest lab report ──
    const latestLab = labs[labs.length - 1] || null;
    const labBlock = (() => {
      if (!latestLab || latestLab.markers.length === 0) {
        return `<p style="padding:14px 0;color:#94a3b8;text-align:center">${d.noLabs}</p>`;
      }
      const headerLine = `<p style="margin:0 0 6px;font-size:12px;color:#64748b">
        <strong>${latestLab.title}</strong> · ${fmtDate(latestLab.reportDate, isAr)}${latestLab.seasonPhase ? ` · ${d.seasonPhase}: ${latestLab.seasonPhase}` : ""}
      </p>`;
      const rows = latestLab.markers
        .map((m) => {
          const hasRange = m.athleteMin !== undefined && m.athleteMax !== undefined;
          const inRange = hasRange ? m.value >= m.athleteMin! && m.value <= m.athleteMax! : null;
          const statusTxt =
            inRange === null
              ? "—"
              : inRange
                ? `<span style="color:#059669;font-weight:600">${d.inRange}</span>`
                : `<span style="color:#dc2626;font-weight:600">${d.outRange}</span>`;
          const rangeTxt = hasRange ? `${m.athleteMin} – ${m.athleteMax}` : "—";
          return `<tr>
            <td style="padding:6px 12px;border-bottom:1px solid #e2e8f0">${m.name}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #e2e8f0;font-weight:600">${m.value} ${m.unit}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #e2e8f0;color:#64748b">${rangeTxt}</td>
            <td style="padding:6px 12px;border-bottom:1px solid #e2e8f0">${statusTxt}</td>
          </tr>`;
        })
        .join("");
      return `${headerLine}
        <table style="width:100%;border-collapse:collapse;font-size:13px">
          <thead>
            <tr style="background:#f0fdf4">
              <th style="padding:8px 12px;text-align:${align};color:#475569;font-weight:600">${d.marker}</th>
              <th style="padding:8px 12px;text-align:${align};color:#475569;font-weight:600">${d.value}</th>
              <th style="padding:8px 12px;text-align:${align};color:#475569;font-weight:600">${d.range}</th>
              <th style="padding:8px 12px;text-align:${align};color:#475569;font-weight:600">${d.statusLbl}</th>
            </tr>
          </thead>
          <tbody>${rows}</tbody>
        </table>`;
    })();

    const periodTxt = bodyComparison
      ? `${fmtDate(bodyComparison.from, isAr)} → ${fmtDate(bodyComparison.to, isAr)}`
      : fmtDate(new Date().toISOString(), isAr);

    const sectionTitle = (txt: string) =>
      `<h2 style="font-size:15px;font-weight:700;color:#0f172a;margin:22px 0 8px;padding-bottom:6px;border-bottom:2px solid #059669">${txt}</h2>`;

    return `<div id="msp-report" dir="${dir}" style="width:760px;background:#ffffff;color:#0f172a;font-family:Arial,'Segoe UI',sans-serif;padding:36px;box-sizing:border-box">
      <!-- Header -->
      <div style="display:flex;align-items:center;justify-content:space-between;border-bottom:3px solid #059669;padding-bottom:16px">
        <div style="display:flex;align-items:center;gap:12px">
          <img src="/images/medisport-icon-192.png" width="52" height="52" style="border-radius:12px" alt="MediSport" />
          <div>
            <div style="font-size:22px;font-weight:800;color:#059669;line-height:1">MediSport</div>
            <div style="font-size:12px;color:#64748b;margin-top:3px">${d.reportTitle}</div>
          </div>
        </div>
        <div style="text-align:${isAr ? "left" : "right"};font-size:12px;color:#64748b">
          <div><strong>${d.athlete}:</strong> ${resolvedName}</div>
          <div><strong>${d.date}:</strong> ${fmtDate(new Date().toISOString(), isAr)}</div>
          <div><strong>${d.period}:</strong> ${periodTxt}</div>
        </div>
      </div>

      ${sectionTitle(d.bodyComp)}
      <table style="width:100%;border-collapse:collapse;font-size:13px">
        <thead>
          <tr style="background:#f0fdf4">
            <th style="padding:8px 12px;text-align:${align};color:#475569;font-weight:600">${d.metric}</th>
            <th style="padding:8px 12px;text-align:${align};color:#475569;font-weight:600">${d.latest}</th>
            <th style="padding:8px 12px;text-align:${align};color:#475569;font-weight:600">${d.change}</th>
          </tr>
        </thead>
        <tbody>${bodyRows}</tbody>
      </table>

      ${sectionTitle(d.bioAgeSec)}
      ${bioBlock}

      ${sectionTitle(d.activitySec)}
      ${actBlock}

      ${sectionTitle(d.labsSec)}
      ${labBlock}

      <!-- Footer -->
      <div style="margin-top:28px;padding-top:14px;border-top:1px solid #e2e8f0;display:flex;justify-content:space-between;font-size:11px;color:#94a3b8">
        <span>${d.generatedBy} · MediSoft</span>
        <span>${d.confidential}</span>
      </div>
    </div>`;
  };

  const handleExport = async () => {
    if (busy) return;
    setBusy(true);
    try {
      const bundle = await fetchBundle();
      const hasAny =
        bundle.body.length > 0 ||
        bundle.bioAge.length > 0 ||
        bundle.activities.length > 0 ||
        bundle.labs.length > 0;
      if (!hasAny) {
        toast.error(d.empty);
        setBusy(false);
        return;
      }

      // Build an off-screen, fully-styled report node (inline RGB styles only,
      // so html2canvas never has to parse oklch/lab CSS functions).
      const wrapper = document.createElement("div");
      wrapper.style.position = "fixed";
      wrapper.style.left = "-10000px";
      wrapper.style.top = "0";
      wrapper.style.zIndex = "-1";
      wrapper.innerHTML = buildReportHtml(bundle);
      document.body.appendChild(wrapper);
      const node = wrapper.querySelector("#msp-report") as HTMLElement;

      // Ensure logo image is loaded before capture.
      const img = node.querySelector("img");
      if (img && !(img as HTMLImageElement).complete) {
        await new Promise<void>((resolve) => {
          img.addEventListener("load", () => resolve(), { once: true });
          img.addEventListener("error", () => resolve(), { once: true });
        });
      }

      const html2canvas = (await import("html2canvas")).default;
      const { jsPDF } = await import("jspdf");

      const canvas = await html2canvas(node, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: "#ffffff",
      });
      document.body.removeChild(wrapper);

      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "a4");
      const imgWidth = 190;
      const pageHeight = 277;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 10;
      let page = 1;

      const footer = (n: number) => {
        pdf.setFontSize(7);
        pdf.setTextColor(170);
        pdf.text("MediSport — MediSoft Health", 105, 293, { align: "center" });
        pdf.text(`${page === n ? n : n}`, 200, 293, { align: "right" });
      };

      pdf.addImage(imgData, "PNG", 10, position, imgWidth, imgHeight);
      footer(page);
      heightLeft -= pageHeight;
      while (heightLeft > 0) {
        pdf.addPage();
        page++;
        position = 10 - (page - 1) * pageHeight;
        pdf.addImage(imgData, "PNG", 10, position, imgWidth, imgHeight);
        footer(page);
        heightLeft -= pageHeight;
      }

      const safeName = resolvedName.replace(/[^\p{L}\p{N}_-]+/gu, "_").slice(0, 40);
      const stamp = new Date().toISOString().slice(0, 10);
      pdf.save(`MediSport_${safeName}_${stamp}.pdf`);
    } catch (err) {
      console.error("[MediSport] PDF export failed:", err);
      toast.error(d.fail);
    } finally {
      setBusy(false);
    }
  };

  return (
    <Button
      type="button"
      variant={variant}
      size={size}
      className={className}
      onClick={handleExport}
      disabled={busy}
    >
      {busy ? (
        <Loader2 className="h-4 w-4 me-1.5 animate-spin" />
      ) : (
        <FileDown className="h-4 w-4 me-1.5" />
      )}
      {busy ? d.preparing : d.exportBtn}
    </Button>
  );
}

export default AthleteProgressPdf;
